In [1]:
# %load ../snippets/start.py
# system packages
import os, sys
import warnings
warnings.filterwarnings('ignore')

# basic wrangling
import numpy as np
import pandas as pd

# eda tools
import missingno as msno
import pandas_profiling
import pickle

In [2]:
# %load ../snippets/visual.py
# must go first
%matplotlib inline
%config InlineBackend.figure_format='retina'

# plotting
import matplotlib as mpl
from matplotlib import pyplot as plt
import seaborn as sns
sns.set_context("poster", font_scale=1.3)

# Update matplotlib defaults to something nicer
mpl_update = {'font.size':16,
              'xtick.labelsize':14,
              'ytick.labelsize':14,
              'figure.figsize':[12.0,8.0],
              'axes.color_cycle':['#0055A7', '#2C3E4F', '#26C5ED', '#00cc66', '#D34100', '#FF9700','#091D32'],
              'axes.labelsize':20,
              'axes.labelcolor':'#677385',
              'axes.titlesize':20,
              'lines.color':'#0055A7',
              'lines.linewidth':3,
              'text.color':'#677385'}
mpl.rcParams.update(mpl_update)

from subprocess import check_output
print(check_output(["ls", "../input"]).decode("utf8"))

samplesubmission.csv
test.csv
train.csv

In [3]:
train_df = pd.read_csv("../input/train.csv")

In [4]:
test_df = pd.read_csv("../input/test.csv")

In [5]:
test_df.shape

(63465, 12)

In [6]:
test_df.head()

,project_id,name,desc,goal,keywords,disable_communication,country,currency,deadline,state_changed_at,created_at,launched_at
0,kkst917493670,Bràthair.,"My first film, of many to come. Trying to purs...",7000.0,brathair,False,US,USD,1449619185,1449619185,1446002581,1446159585
1,kkst1664901914,THE SCREENWRITER,A young man that has earned his master's in sc...,35000.0,the-screenwriter,False,US,USD,1453435620,1453435620,1450297323,1450411620
2,kkst925125077,The Hornets Nest the Fairmont Heights Story,Film about a high school constructed for negro...,49500.0,the-hornets-nest-the-fairmont-heights-story,False,US,USD,1451780700,1451780700,1448581356,1448672128
3,kkst1427645275,BROTHERS Season 2 - Groundbreaking Transgender...,The acclaimed series about a group of transgen...,40000.0,brothers-season-2-groundbreaking-transgender-male,False,US,USD,1445021518,1445021530,1440966830,1442429518
4,kkst1714249266,Blackdom the movie,Blackdom's history offers a new narrative tha...,20000.0,blackdom-the-movie,False,US,USD,1462068840,1462068844,1455765276,1458334890

In [7]:
train_df.shape

(108129, 14)

In [8]:
train_df.head()

,project_id,name,desc,goal,keywords,disable_communication,country,currency,deadline,state_changed_at,created_at,launched_at,backers_count,final_status
0,kkst1451568084,drawing for dollars,I like drawing pictures. and then i color them...,20.0,drawing-for-dollars,False,US,USD,1241333999,1241334017,1240600507,1240602723,3,1
1,kkst1474482071,Sponsor Dereck Blackburn (Lostwars) Artist in ...,"I, Dereck Blackburn will be taking upon an inc...",300.0,sponsor-dereck-blackburn-lostwars-artist-in-re...,False,US,USD,1242429000,1242432018,1240960224,1240975592,2,0
2,kkst183622197,Mr. Squiggles,So I saw darkpony's successfully funded drawin...,30.0,mr-squiggles,False,US,USD,1243027560,1243027818,1242163613,1242164398,0,0
3,kkst597742710,Help me write my second novel.,Do your part to help out starving artists and ...,500.0,help-me-write-my-second-novel,False,US,USD,1243555740,1243556121,1240963795,1240966730,18,1
4,kkst1913131122,Support casting my sculpture in bronze,"I'm nearing completion on a sculpture, current...",2000.0,support-casting-my-sculpture-in-bronze,False,US,USD,1243769880,1243770317,1241177914,1241180541,1,0

In [9]:
train_df['final_status'].value_counts()

0    73568
1    34561
Name: final_status, dtype: int64

In [10]:
train_df['disable_communication'].value_counts()

False    107806
True        323
Name: disable_communication, dtype: int64

In [11]:
train_df['country'].value_counts()

US    92033
GB     8758
CA     3736
AU     1880
NL      705
NZ      355
SE      240
DK      196
NO      114
IE      111
DE        1
Name: country, dtype: int64

In [12]:
train_df['currency'].value_counts()

USD    92033
GBP     8758
CAD     3736
AUD     1880
EUR      817
NZD      355
SEK      240
DKK      196
NOK      114
Name: currency, dtype: int64

In [13]:
test_df.isnull().sum()

project_id               0
name                     0
desc                     4
goal                     0
keywords                 0
disable_communication    0
country                  0
currency                 0
deadline                 0
state_changed_at         0
created_at               0
launched_at              0
dtype: int64

In [14]:
train_df.isnull().sum()

project_id               0
name                     3
desc                     9
goal                     0
keywords                 0
disable_communication    0
country                  0
currency                 0
deadline                 0
state_changed_at         0
created_at               0
launched_at              0
backers_count            0
final_status             0
dtype: int64

In [15]:
train_df = train_df.dropna()

In [16]:
test_df = test_df.fillna(0)

In [17]:
test_df.columns

Index(['project_id', 'name', 'desc', 'goal', 'keywords',
       'disable_communication', 'country', 'currency', 'deadline',
       'state_changed_at', 'created_at', 'launched_at'],
      dtype='object')

In [18]:
train_df.columns

Index(['project_id', 'name', 'desc', 'goal', 'keywords',
       'disable_communication', 'country', 'currency', 'deadline',
       'state_changed_at', 'created_at', 'launched_at', 'backers_count',
       'final_status'],
      dtype='object')

# Dataset Creation for Tree Based Models

In [19]:
c_features = train_df[['disable_communication','country', 'currency']]

In [20]:
c_features_test = test_df[['disable_communication','country', 'currency']]

In [21]:
n_features = train_df[['goal','backers_count']]

In [22]:
n_features_test = test_df[['goal']]

In [23]:
dt_features = train_df[['deadline','state_changed_at', 'created_at', 'launched_at']]

In [24]:
dt_features_test = test_df[['deadline','state_changed_at', 'created_at', 'launched_at']]

In [25]:
text_features = train_df[['name', 'desc','keywords']]

In [26]:
text_features_test = test_df[['name', 'desc','keywords']]

In [27]:
from sklearn.preprocessing import LabelEncoder

In [28]:
class_le = LabelEncoder()

In [29]:
tree_c_features = c_features.apply(class_le.fit_transform)

In [30]:
tree_c_features_test = c_features_test.apply(class_le.fit_transform)

In [31]:
dt_features['deadline'] = pd.to_datetime(dt_features['deadline'],unit='s')

In [32]:
dt_features_test['deadline'] = pd.to_datetime(dt_features_test['deadline'],unit='s')

In [33]:
dt_features['state_changed_at'] = pd.to_datetime(dt_features['state_changed_at'],unit='s')

In [34]:
dt_features_test['state_changed_at'] = pd.to_datetime(dt_features_test['state_changed_at'],unit='s')

In [35]:
dt_features['created_at'] = pd.to_datetime(dt_features['created_at'],unit='s')

In [36]:
dt_features_test['created_at'] = pd.to_datetime(dt_features_test['created_at'],unit='s')

In [37]:
dt_features['launched_at'] = pd.to_datetime(dt_features['launched_at'],unit='s')

In [38]:
dt_features_test['launched_at'] = pd.to_datetime(dt_features_test['launched_at'],unit='s')

In [39]:
final_df_test = dt_features_test.join(tree_c_features_test)

In [40]:
final_df = dt_features.join(tree_c_features)

In [41]:
final_df = final_df.join(n_features)

In [42]:
final_df_test = final_df_test.join(n_features_test)

In [43]:
final_df['final_status'] = train_df['final_status']

In [44]:
final_df_test

,deadline,state_changed_at,created_at,launched_at,disable_communication,country,currency,goal
0,2015-12-08 23:59:45,2015-12-08 23:59:45,2015-10-28 03:23:01,2015-10-29 22:59:45,0,20,12,7000.0
1,2016-01-22 04:07:00,2016-01-22 04:07:00,2015-12-16 20:22:03,2015-12-18 04:07:00,0,20,12,35000.0
2,2016-01-03 00:25:00,2016-01-03 00:25:00,2015-11-26 23:42:36,2015-11-28 00:55:28,0,20,12,49500.0
3,2015-10-16 18:51:58,2015-10-16 18:52:10,2015-08-30 20:33:50,2015-09-16 18:51:58,0,20,12,40000.0
4,2016-05-01 02:14:00,2016-05-01 02:14:04,2016-02-18 03:14:36,2016-03-18 21:01:30,0,20,12,20000.0
5,2016-04-27 17:26:34,2016-04-27 17:26:34,2016-03-16 23:40:26,2016-03-28 17:26:34,0,20,12,10000.0
6,2015-12-14 10:03:43,2015-12-14 10:03:43,2015-11-08 14:56:59,2015-11-14 10:03:43,0,12,4,1000.0
7,2016-02-26 20:00:00,2016-02-26 20:00:01,2015-12-24 13:47:17,2015-12-28 22:03:04,0,9,5,300.0
8,2015-10-08 20:59:00,2015-10-08 20:59:01,2015-09-08 20:59:17,2015-09-08 22:16:04,0,20,12,6000.0
9,2015-10-06 15:10:22,2015-10-06 15:10:23,2015-08-06 18:40:15,2015-09-01 15:10:22,0,20,12,8000.0
10,2015-07-10 22:08:55,2015-07-10 22:08:56,2015-06-08 09:15:39,2015-06-10 22:08:55,0,20,12,25000.0
11,2015-10-01 05:00:00,2015-10-01 05:00:13,2015-09-01 04:09:37,2015-09-02 01:33:12,0,20,12,12000.0
12,2015-09-19 03:50:17,2015-09-19 03:50:17,2015-08-19 23:19:44,2015-08-20 03:50:17,0,20,12,5000.0
13,2016-04-16 20:08:40,2016-04-16 20:08:40,2016-02-15 02:38:09,2016-02-16 21:08:40,0,20,12,6300.0
14,2015-08-16 14:06:41,2015-08-16 14:06:42,2015-07-14 14:33:47,2015-07-17 14:15:47,0,20,12,50000.0
15,2016-02-17 23:59:00,2016-02-17 23:59:00,2016-01-04 17:06:54,2016-01-06 05:31:22,0,9,5,4400.0
16,2016-04-01 06:59:00,2016-04-01 06:59:01,2014-08-25 22:01:30,2016-02-29 07:50:25,0,20,12,50000.0
17,2016-03-25 14:57:29,2016-03-25 14:57:29,2016-01-22 09:45:55,2016-01-25 15:57:29,0,9,5,2000.0
18,2016-04-14 12:40:04,2016-04-14 12:40:04,2015-12-29 15:53:26,2016-03-15 12:40:04,0,9,5,6000.0
19,2015-10-29 22:04:17,2015-10-29 22:04:19,2015-09-07 18:09:45,2015-09-29 22:04:17,0,12,4,3000.0
20,2015-10-08 22:07:00,2015-10-08 22:07:00,2015-08-23 16:51:39,2015-09-10 00:31:03,0,20,12,20000.0
21,2015-06-22 17:48:15,2015-06-22 17:48:18,2015-05-02 12:33:48,2015-05-23 17:48:15,0,9,5,3423.0
22,2015-07-21 06:59:00,2015-07-21 06:59:01,2015-06-18 16:48:57,2015-06-27 05:37:37,0,20,12,5000.0
23,2016-06-16 15:37:26,2016-06-16 15:37:28,2016-06-06 03:34:17,2016-06-06 15:37:26,0,20,12,12000.0
24,2015-10-02 10:35:38,2015-10-02 10:35:38,2015-08-23 08:24:49,2015-08-23 10:35:38,0,1,0,5000.0
25,2016-03-06 23:55:31,2016-03-06 23:55:32,2016-01-06 00:57:53,2016-01-06 23:55:31,0,9,5,2500.0
26,2015-10-10 21:00:00,2015-10-10 21:00:14,2015-09-05 14:22:58,2015-09-12 13:01:38,0,9,5,3500.0
27,2016-01-27 06:44:33,2016-01-27 06:44:33,2016-01-20 02:53:09,2016-01-20 06:44:33,0,20,12,16500.0
28,2015-07-12 17:21:00,2015-07-12 17:21:00,2015-06-11 17:21:24,2015-06-11 18:29:58,0,20,12,50000.0
29,2016-03-20 09:33:24,2016-03-20 09:33:24,2016-02-06 14:01:49,2016-02-19 10:33:24,0,9,5,15000.0
...,...,...,...,...,...,...,...,...
63435,2016-06-15 02:25:00,2016-06-15 02:25:02,2016-05-05 02:39:23,2016-05-16 03:10:47,0,20,12,9000.0
63436,2016-11-19 21:47:32,2016-11-19 21:47:32,2016-10-17 12:28:51,2016-10-22 20:47:32,0,20,12,100000.0
63437,2015-11-21 06:41:35,2015-11-21 06:41:35,2015-10-16 03:15:17,2015-10-17 05:41:35,0,3,1,1000.0
63438,2015-12-14 20:05:32,2015-12-14 20:05:32,2015-10-28 20:17:49,2015-11-04 20:05:32,0,12,4,3000.0
63439,2015-09-12 06:28:46,2015-09-12 06:28:46,2015-08-04 05:46:43,2015-08-13 06:28:46,0,1,0,9000.0
63440,2017-03-24 02:05:51,2017-03-24 02:05:52,2017-01-31 17:53:18,2017-02-22 03:05:51,0,20,12,13000.0
63441,2015-11-18 01:17:26,2015-11-18 01:17:26,2015-10-03 17:43:01,2015-10-19 00:17:26,0,17,9,2500.0
63442,2015-08-07 00:52:06,2015-08-07 00:52:06,2015-07-07 23:50:14,2015-07-08 00:52:06,0,20,12,6000.0
63443,2017-01-15 01:24:12,2017-01-15 01:24:13,2016-12-15 06:16:26,2016-12-16 01:24:12,0,20,12,7000.0
63444,2016-09-05 20:45:53,2016-09-05 20:45:53,2016-07-07 01:44:41,2016-07-07 20:45:53,0,20,12,7000.0
63445,2016-12-18 20:15:58,2016-12-18 20:16:00,2016-10-12 23:00:27,2016-10-19 19:15:58,0,20,12,5500.0
63446,2015-10-31 11:00:32,2015-10-31 11:00:32,2015-08-26 15:18:25,2015-10-01 11:00:32,0,9,5,4150.0
63447,2015-11-02 01:05:18,2015-11-02 01:05:18,2015-09-02 22:47:03,2015-09-03 00:05:18,0,20,12,27000.0
63448,2017-01-13 21:13:15,2017-01-13 21:13:15,2016-12-30 22:44:16,2017-01-06 21:13:15,0,1,0,400.0
63449,2015-09-11 16:33:32,2015-09-11 16:33:32,2015-03-25 14:25:12,2015-08-18 16:33:32,0,15,4,10400.0
63450,2015-07-01 04:59:00,2015-07-01 04:59:02,2015-05-01 01:57:08,2015-05-29 20:28:26,0,20,12,9000.0
63451,2015-06-15 22:58:02,2015-06-15 22:58:03,2015-05-27 17:06:40,2015-06-01 22:58:02,0,20,12,5000.0
63452,2016-01-01 04:59:00,2016-01-01 04:59:00,2015-11-17 01:36:11,2015-11-21 20:27:38,0,20,12,2500.0
63453,2015-06-20 16:25:31,2015-06-20 16:25:32,2015-04-18 02:57:56,2015-05-21 16:25:31,0,20,12,1800.0
63454,2016-03-09 22:51:04,2016-03-09 22:51:05,2016-02-07 00:09:45,2016-02-08 22:51:04,0,9,5,2000.0
63455,2016-09-08 22:25:31,2016-09-08 22:25:31,2016-06-24 18:43:10,2016-08-09 22:25:31,0,20,12,2500.0
63456,2016-01-14 20:53:23,2016-01-14 20:53:25,2015-11-10 19:34:52,2015-11-15 20:53:23,0,9,5,60000.0
63457,2016-11-27 12:17:55,2016-11-27 12:17:56,2016-11-01 08:44:20,2016-11-07 12:17:55,0,17,9,3500.0
63458,2015-12-09 16:40:45,2015-12-09 16:40:45,2015-11-07 20:01:29,2015-11-09 16:40:45,0,20,12,4444.0
63459,2016-07-31 00:59:00,2016-07-31 00:59:00,2014-04-14 01:17:47,2016-06-01 01:03:51,0,20,12,2000.0
63460,2015-07-01 02:00:00,2015-07-01 02:00:12,2015-04-11 00:15:15,2015-05-08 20:16:33,0,20,12,6000.0
63461,2015-10-26 09:48:27,2015-10-26 09:48:28,2015-09-04 01:15:21,2015-09-11 09:48:27,0,20,12,1500.0
63462,2016-06-01 15:39:00,2016-06-01 15:39:00,2016-04-25 15:27:58,2016-04-25 16:29:59,0,3,1,4000.0
63463,2016-06-11 16:50:10,2016-06-11 16:50:10,2016-03-29 17:11:38,2016-04-12 16:50:10,0,20,12,42800.0
63464,2015-09-07 05:42:28,2015-09-07 05:42:28,2015-08-23 04:11:33,2015-08-23 05:42:28,0,20,12,850.0

In [45]:
import pickle

In [46]:
pickle.dump(final_df,open('../proxy/dataset1','wb'))

In [46]:
pickle.dump(final_df_test,open('../proxy/dataset1_test','wb'))

In [47]:
text_features = train_df[['name', 'desc','keywords']]

In [48]:
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import LabelEncoder
import re
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [49]:
stops = set(stopwords.words("english"))
def cleanData(text, lowercase = False, remove_stops = False, stemming = False):
    txt = str(text)
    txt = re.sub(r'[^A-Za-z0-9\s]',r'',txt)
    txt = re.sub(r'\n',r' ',txt)
    
    if lowercase:
        txt = " ".join([w.lower() for w in txt.split()])
        
    if remove_stops:
        txt = " ".join([w for w in txt.split() if w not in stops])
    
    if stemming:
        st = PorterStemmer()
        txt = " ".join([st.stem(w) for w in txt.split()])

    return txt

In [50]:
train_df['desc'] = train_df['desc'].map(lambda x: cleanData(x, lowercase=True, remove_stops=True, stemming=True))

In [51]:
# initialise the functions - we'll create separate models for each type.
countvec = CountVectorizer(analyzer='word', ngram_range = (1,1),max_features=500)
tfidfvec = TfidfVectorizer(analyzer='word', ngram_range = (1,1),max_features=500)

In [52]:
bagofwords = countvec.fit_transform(train_df['desc'])
tfidfdata = tfidfvec.fit_transform(train_df['desc'])

In [53]:
bow_df = pd.DataFrame(bagofwords.todense())
tfidf_df = pd.DataFrame(tfidfdata.todense())

In [54]:
bow_df

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
0,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,2,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
24,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
27,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
29,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108089,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
108090,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
108091,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
108092,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
108093,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
108094,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
108095,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
108096,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
108097,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
108098,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
108099,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
108100,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
108101,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
108102,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
108103,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
108104,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
108105,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
108106,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
108107,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
108108,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
108109,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
108110,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
108111,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
108112,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
108113,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
108114,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
108115,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
108116,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
108117,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
108118,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [55]:
bow_df.columns = ['col'+ str(x) for x in bow_df.columns]
tfidf_df.columns = ['col' + str(x) for x in tfidf_df.columns]

In [56]:
pickle.dump(bow_df,open('../proxy/dataset3_textb','wb'))

In [57]:
pickle.dump(tfidf_df,open('../proxy/dataset3_texttf','wb'))

In [58]:
bow_df_df.shape

(108119, 500)